package output.com.lenovo.datahub.dao;

import output.com.lenovo.datahub.domain.Kettest;

public interface KettestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KETTEST
     *
     * @mbggenerated
     */
    int insert(Kettest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KETTEST
     *
     * @mbggenerated
     */
    int insertSelective(Kettest record);
}